### ISSUE TITLE
Does not start on macOS Monterey

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/barge#273] opened 2021-11-29 11:56 UTC
As Aquarius is using `5000` as a port, starting it up won't work on macOS Monterey which uses that port for being an AirPlay Receiver. 

We will not tell every macOS user to change the port of this feature or to turn it off, so #272 should be the best solution.

**Comment by AnaLoznianu** [comment] 2021-12-07 13:50
Closing this as a duplicate of: https://github.com/oceanprotocol/barge/issues/272

**Closed by AnaLoznianu** 2021-12-07 13:50 UTC
Labels: Type: Bug
